engines:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
plugins:
  bundler-audit:
    enabled: true
  rubocop:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
ratings:
  paths:
  - "**.rb"
exclude_paths:
- "ext/"
- "ports/"
- "test/"
- "tmp/"
exclude_patterns:
- "features/"
- "script/"
- "**/vendor/"
